from __future__ import annotations

from fastapi import Depends, FastAPI

from .auth import get_current_user_id
from .db_client import FakeMediaDbClient
from .schemas import UploadUrlRequest, UploadUrlResponse
from .storage_client import generate_upload_url, get_media_bucket


app = FastAPI(title="WildLens Media Service", version="0.1.0")


def get_db_client() -> FakeMediaDbClient:
    return FakeMediaDbClient()


def build_object_path(owner_id: str, checksum_sha256: str, filename: str) -> str:
    return f"incoming/{owner_id}/{checksum_sha256}/{filename}"


@app.post("/media/upload-url", response_model=UploadUrlResponse)
def create_upload_url(
    request: UploadUrlRequest,
    owner_id: str = Depends(get_current_user_id),
    db_client: FakeMediaDbClient = Depends(get_db_client),
) -> UploadUrlResponse:
    file_id = request.checksum_sha256
    existing_media = db_client.find_by_checksum(request.checksum_sha256)

    if existing_media:
        return UploadUrlResponse(
            duplicate=True,
            file_id=file_id,
            existing_file_url=existing_media.file_url,
            existing_thumbnail_url=existing_media.thumbnail_url,
            message="File already exists for this checksum.",
        )

    object_path = build_object_path(owner_id, request.checksum_sha256, request.filename)
    bucket = get_media_bucket()
    upload_url = generate_upload_url(bucket, object_path, request.content_type)

    return UploadUrlResponse(
        duplicate=False,
        file_id=file_id,
        upload_url=upload_url,
        bucket=bucket,
        object_path=object_path,
        message="Upload URL generated by local placeholder storage client.",
    )
